title: "Causality & Policy Evaluation Research Group"
description: "Tzu-Ting Yang (楊子霆) @ Institute of Economics, Academia Sinica"
url: "https://ttyangsinica.github.io"
baseurl: ""
lang: "en"

author:
  name: "Tzu-Ting Yang"
  name_zh: "楊子霆"
  email: "ttyang@econ.sinica.edu.tw"
  affiliation: "Institute of Economics, Academia Sinica"
  location: "Taipei, Taiwan"
  cv: "/CV/CV.pdf"

nav:
  - title: "Home"
    url: "/"
  - title: "Research"
    url: "/research/"
  - title: "Teaching"
    url: "/teaching/"
  - title: "Members"
    url: "/members/"
  - title: "Join us"
    url: "/join-us/"

markdown: kramdown
permalink: pretty

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
